import { Footer } from "@/components/Fotter";
import { Header } from "@/components/Header";
import { MyUserContextProvider } from "@/utils/useUser";
import "./globals.css";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <MyUserContextProvider>
          <SupabaseProvider>
            {children}
          </SupabaseProvider>
        </MyUserContextProvider>
        <Footer />
      </body>
    </html>
  );
}
